Search.appendIndex(
    [
                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao",
            "name": "MarcadorDocumentacao",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html"
        },                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao\u003A\u003ArotuloDe\u0028\u0029",
            "name": "rotuloDe",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html#method_rotuloDe"
        },                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao\u003A\u003AentradaBase\u0028\u0029",
            "name": "entradaBase",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html#method_entradaBase"
        },                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao\u003A\u003AnomeCurtoDe\u0028\u0029",
            "name": "nomeCurtoDe",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html#method_nomeCurtoDe"
        },                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao\u003A\u003AfqnDe\u0028\u0029",
            "name": "fqnDe",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html#method_fqnDe"
        },                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao\u003A\u003AtipoParaString\u0028\u0029",
            "name": "tipoParaString",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html#method_tipoParaString"
        },                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao\u003A\u003A\u0024iProxId",
            "name": "iProxId",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html#property_iProxId"
        },                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao\u003A\u003A\u0024aPilhaClasse",
            "name": "aPilhaClasse",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html#property_aPilhaClasse"
        },                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao\u003A\u003A\u0024oFind",
            "name": "oFind",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html#property_oFind"
        },                {
            "fqsen": "\\Analyser\\MarcadorDocumentacao\u003A\u003A\u0024oPP",
            "name": "oPP",
            "summary": "",
            "url": "classes/Analyser-MarcadorDocumentacao.html#property_oPP"
        },                {
            "fqsen": "\\Generator\\AplicadorDocumentacao",
            "name": "AplicadorDocumentacao",
            "summary": "",
            "url": "classes/Generator-AplicadorDocumentacao.html"
        },                {
            "fqsen": "\\Generator\\AplicadorDocumentacao\u003A\u003AparaDocblockComIdentacao\u0028\u0029",
            "name": "paraDocblockComIdentacao",
            "summary": "",
            "url": "classes/Generator-AplicadorDocumentacao.html#method_paraDocblockComIdentacao"
        },                {
            "fqsen": "\\Generator\\ClienteGPT",
            "name": "ClienteGPT",
            "summary": "",
            "url": "classes/Generator-ClienteGPT.html"
        },                {
            "fqsen": "\\Generator\\ConstrutorPrompt",
            "name": "ConstrutorPrompt",
            "summary": "",
            "url": "classes/Generator-ConstrutorPrompt.html"
        },                {
            "fqsen": "\\App\\Parser\\Normalizador",
            "name": "Normalizador",
            "summary": "",
            "url": "classes/App-Parser-Normalizador.html"
        },                {
            "fqsen": "\\App\\Parser\\ServicoAst",
            "name": "ServicoAst",
            "summary": "",
            "url": "classes/App-Parser-ServicoAst.html"
        },                {
            "fqsen": "\\Util\\InjetorPlaceholder",
            "name": "InjetorPlaceholder",
            "summary": "Classe\u0020respons\u00E1vel\u0020por\u0020injetar\u0020placeholders\u0020em\u0020um\u0020arquivo\u0020de\u0020entrada\u0020com\u0020base\u0020em\u0020um\u0020mapa\u0020de\u0020itens.",
            "url": "classes/Util-InjetorPlaceholder.html"
        },                {
            "fqsen": "\\Util\\RelatorErros",
            "name": "RelatorErros",
            "summary": "",
            "url": "classes/Util-RelatorErros.html"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Analyser",
            "name": "Analyser",
            "summary": "",
            "url": "namespaces/analyser.html"
        },                {
            "fqsen": "\\Generator",
            "name": "Generator",
            "summary": "",
            "url": "namespaces/generator.html"
        },                {
            "fqsen": "\\App\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "namespaces/app-parser.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\Util",
            "name": "Util",
            "summary": "",
            "url": "namespaces/util.html"
        }            ]
);
