name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
        tools: composer

    - name: Composer install
      run: composer install --no-interaction --prefer-dist

    - name: Lint + CS + Static
      run: |
        vendor/bin/phpcs --standard=PSR12 src bin || true
        vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no
        vendor/bin/phpstan analyse src --level=max

    - name: Generate test stubs (idempotent)
      run: composer gen-tests

    - name: PHPUnit
      run: composer test

    - name: Run DocGen smoke
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_MODEL: gpt-4o-mini
      run: php bin/run.php --base ci

    - name: Build phpDocumentor
      run: vendor/bin/phpdoc -c phpdoc.xml

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docgen-output
        path: |
          output/**
          docs/**

    - name: Notify n8n
      if: always()
      run: |
        curl -X POST '${{ secrets.N8N_WEBHOOK_URL }}' \
          -H 'Content-Type: application/json' \
          -d @- <<'JSON'
        {
          "repo": "${{ github.repository }}",
          "branch": "${{ github.ref_name }}",
          "commit": "${{ github.sha }}",
          "actor": "${{ github.actor }}",
          "run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          "status": "${{ job.status }}",
          "artifacts": ["docgen-output"],
          "docs_url": "https://$GITHUB_REPOSITORY_OWNER.github.io/${{ github.event.repository.name }}/"
        }
JSON

  deploy-pages:
    if: github.ref == 'refs/heads/main'
    needs: build-test-docs
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: docgen-output
        path: .
    - uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v3
      with:
        path: docs
    - uses: actions/deploy-pages@v4
